'use strict'
const router = require('express').Router()
const { authMiddleware, optionalAuth } = require('../auth')
const ctrl = require('../controllers/calendars.controller')
const rest = require('../controllers/restaurant.controller')
const cine = require('../controllers/cinema.controller')
const hotel = require('../controllers/hotel.controller')
const pms = require('../controllers/hotelPms.controller')
const chan = require('../controllers/hotelChannels.controller')

// ── Gestión (autenticado) ────────────────────────────────────────────────────
router.get('/accounts/:accId/calendars',                 authMiddleware, ctrl.list)
router.post('/accounts/:accId/calendars',                authMiddleware, ctrl.create)
router.get('/accounts/:accId/calendars/:calId',          authMiddleware, ctrl.get)
router.put('/accounts/:accId/calendars/:calId',          authMiddleware, ctrl.update)
router.delete('/accounts/:accId/calendars/:calId',       authMiddleware, ctrl.remove)
router.get('/accounts/:accId/calendars/:calId/availability', authMiddleware, ctrl.availability)
router.get('/accounts/:accId/calendars/:calId/month-availability', authMiddleware, ctrl.monthAvailability)

// Reservas
router.get('/accounts/:accId/calendars/:calId/bookings',     authMiddleware, ctrl.listBookings)
router.post('/accounts/:accId/calendars/:calId/bookings',    authMiddleware, ctrl.createBooking)
router.get('/accounts/:accId/calendars/:calId/bookings/export', authMiddleware, ctrl.exportBookings)
router.put('/accounts/:accId/bookings/:bookingId',           authMiddleware, ctrl.updateBooking)
router.post('/accounts/:accId/bookings/:bookingId/reschedule', authMiddleware, ctrl.rescheduleBooking)
router.post('/accounts/:accId/bookings/:bookingId/status',   authMiddleware, ctrl.setStatus)
router.delete('/accounts/:accId/bookings/:bookingId',        authMiddleware, ctrl.deleteBooking)
router.get('/accounts/:accId/bookings/:bookingId/chat',      authMiddleware, ctrl.bookingChat)
// Agenda general: reservas de todos los calendarios + tareas del CRM en un rango.
router.get('/accounts/:accId/agenda',                        authMiddleware, ctrl.agenda)
// Cliente / paciente / huésped — historial (datos + reservas)
router.get('/accounts/:accId/customers/:customerId/history', authMiddleware, ctrl.customerHistory)

// ── Restaurante (Fase 2): mesas, turnos, waitlist ────────────────────────────
router.get('/accounts/:accId/calendars/:calId/tables',     authMiddleware, rest.listTables)
router.post('/accounts/:accId/calendars/:calId/tables',    authMiddleware, rest.createTable)
router.put('/accounts/:accId/tables/:tableId',             authMiddleware, rest.updateTable)
router.delete('/accounts/:accId/tables/:tableId',          authMiddleware, rest.deleteTable)
router.get('/accounts/:accId/calendars/:calId/shifts',     authMiddleware, rest.listShifts)
router.post('/accounts/:accId/calendars/:calId/shifts',    authMiddleware, rest.createShift)
router.put('/accounts/:accId/shifts/:shiftId',             authMiddleware, rest.updateShift)
router.delete('/accounts/:accId/shifts/:shiftId',          authMiddleware, rest.deleteShift)
router.get('/accounts/:accId/calendars/:calId/waitlist',   authMiddleware, rest.listWaitlist)
router.post('/accounts/:accId/calendars/:calId/waitlist',  authMiddleware, rest.addWaitlist)
router.put('/accounts/:accId/waitlist/:wid',               authMiddleware, rest.updateWaitlist)

// ── Cine (Fase 3): config (autenticado) ──────────────────────────────────────
router.get('/accounts/:accId/calendars/:calId/movies',      authMiddleware, cine.listMovies)
router.post('/accounts/:accId/calendars/:calId/movies',     authMiddleware, cine.createMovie)
router.put('/accounts/:accId/movies/:movieId',              authMiddleware, cine.updateMovie)
router.delete('/accounts/:accId/movies/:movieId',           authMiddleware, cine.deleteMovie)
router.get('/accounts/:accId/calendars/:calId/auditoriums', authMiddleware, cine.listAuditoriums)
router.post('/accounts/:accId/calendars/:calId/auditoriums',authMiddleware, cine.createAuditorium)
router.put('/accounts/:accId/auditoriums/:audId',           authMiddleware, cine.updateAuditorium)
router.delete('/accounts/:accId/auditoriums/:audId',        authMiddleware, cine.deleteAuditorium)
router.get('/accounts/:accId/calendars/:calId/showtimes',   authMiddleware, cine.listShowtimes)
router.post('/accounts/:accId/calendars/:calId/showtimes',  authMiddleware, cine.createShowtime)
router.put('/accounts/:accId/showtimes/:showId',            authMiddleware, cine.updateShowtime)
router.delete('/accounts/:accId/showtimes/:showId',         authMiddleware, cine.deleteShowtime)
// ── Cine: flujo público de compra ────────────────────────────────────────────
router.get('/public/cinema/:accId/:calId/listing',          optionalAuth, cine.publicListing)
router.get('/public/cinema/:accId/showtimes/:showId/seats', optionalAuth, cine.publicSeatMap)
router.post('/public/cinema/:accId/showtimes/:showId/hold', optionalAuth, cine.publicHold)
router.post('/public/cinema/:accId/showtimes/:showId/release', optionalAuth, cine.publicRelease)
router.post('/public/cinema/:accId/showtimes/:showId/book', optionalAuth, cine.publicBook)

// ── Hotel (Fase 4a): config (autenticado) ────────────────────────────────────
router.get('/accounts/:accId/calendars/:calId/room-types',  authMiddleware, hotel.listRoomTypes)
router.post('/accounts/:accId/calendars/:calId/room-types', authMiddleware, hotel.createRoomType)
router.put('/accounts/:accId/room-types/:rtId',             authMiddleware, hotel.updateRoomType)
router.delete('/accounts/:accId/room-types/:rtId',          authMiddleware, hotel.deleteRoomType)
router.get('/accounts/:accId/room-types/:rtId/rates',       authMiddleware, hotel.listRates)
router.post('/accounts/:accId/room-types/:rtId/rates',      authMiddleware, hotel.setRates)
router.delete('/accounts/:accId/room-types/:rtId/rates',    authMiddleware, hotel.clearRate)
// ── Hotel: flujo público de reserva ──────────────────────────────────────────
router.get('/public/hotel/:accId/:calId/search',            optionalAuth, hotel.publicSearch)
router.get('/public/hotel/:accId/:calId/quote',             optionalAuth, hotel.publicQuote)
router.post('/public/hotel/:accId/:calId/book',             optionalAuth, hotel.publicBook)
// ── Hotel PMS operativo (Fases 4b-4e, autenticado) ───────────────────────────
router.get('/accounts/:accId/calendars/:calId/rooms',       authMiddleware, pms.listRooms)
router.post('/accounts/:accId/calendars/:calId/rooms',      authMiddleware, pms.createRoom)
router.put('/accounts/:accId/rooms/:roomId',                authMiddleware, pms.updateRoom)
router.delete('/accounts/:accId/rooms/:roomId',             authMiddleware, pms.deleteRoom)
router.put('/accounts/:accId/rooms/:roomId/hk',             authMiddleware, pms.setRoomHk)
router.get('/accounts/:accId/calendars/:calId/arrivals',    authMiddleware, pms.arrivals)
router.get('/accounts/:accId/calendars/:calId/departures',  authMiddleware, pms.departures)
router.get('/accounts/:accId/calendars/:calId/inhouse',     authMiddleware, pms.inHouse)
router.post('/accounts/:accId/calendars/:calId/walkin',     authMiddleware, pms.walkIn)
router.post('/accounts/:accId/bookings/:bookingId/checkin', authMiddleware, pms.checkIn)
router.post('/accounts/:accId/bookings/:bookingId/checkout',authMiddleware, pms.checkOut)
router.post('/accounts/:accId/bookings/:bookingId/change-room', authMiddleware, pms.changeRoom)
router.get('/accounts/:accId/calendars/:calId/hk-tasks',    authMiddleware, pms.listHk)
router.post('/accounts/:accId/calendars/:calId/hk-tasks',   authMiddleware, pms.createHk)
router.put('/accounts/:accId/hk-tasks/:taskId',             authMiddleware, pms.updateHk)
router.get('/accounts/:accId/calendars/:calId/maintenance', authMiddleware, pms.listMnt)
router.post('/accounts/:accId/calendars/:calId/maintenance',authMiddleware, pms.createMnt)
router.put('/accounts/:accId/maintenance/:mntId/resolve',   authMiddleware, pms.resolveMnt)
router.get('/accounts/:accId/bookings/:bookingId/folio',    authMiddleware, pms.getFolio)
router.post('/accounts/:accId/bookings/:bookingId/folio/charge',  authMiddleware, pms.addCharge)
router.post('/accounts/:accId/bookings/:bookingId/folio/payment', authMiddleware, pms.addPayment)
router.get('/accounts/:accId/calendars/:calId/report',      authMiddleware, pms.report)

// ── Hotel: canales / OTAs (Airbnb, HosRoom, Booking, Kunas) ──────────────────
router.get('/accounts/:accId/calendars/:calId/channels',    authMiddleware, chan.list)
router.post('/accounts/:accId/calendars/:calId/channels',   authMiddleware, chan.create)
router.put('/accounts/:accId/channels/:chanId',             authMiddleware, chan.update)
router.delete('/accounts/:accId/channels/:chanId',          authMiddleware, chan.remove)
router.post('/accounts/:accId/channels/:chanId/sync',       authMiddleware, chan.sync)
router.get('/accounts/:accId/channel-providers',            authMiddleware, chan.schemas)
router.post('/accounts/:accId/channels/:chanId/test',       authMiddleware, chan.test)
router.post('/accounts/:accId/channels/:chanId/import-rooms', authMiddleware, chan.importRooms)
// Público: iCal export (la OTA se suscribe) + webhook de reserva entrante.
router.get('/public/hotel/:accId/:calId/ical/:roomTypeId.ics', chan.ical)
router.post('/public/hotel/:accId/:calId/channels/:provider/reservation', chan.inbound)

// ── Público (página de reservas / formulario) ────────────────────────────────
router.get('/public/calendars/:accId/:calId',                optionalAuth, ctrl.getPublic)
router.get('/public/calendars/:accId/:calId/availability',   optionalAuth, ctrl.getPublicAvailability)
router.get('/public/calendars/:accId/:calId/month-availability', optionalAuth, ctrl.getPublicMonthAvailability)
router.post('/public/calendars/:accId/:calId/book',          optionalAuth, ctrl.createPublicBooking)
// Operaciones de los nodos de flujo del navegador (pruebas/webchat).
router.post('/public/calendars/:accId/flow-op',              optionalAuth, ctrl.flowOp)
// Festivos por país (público — lo usa la UI de calendario y la página de reservas).
router.get('/holidays/:country/:year',                       ctrl.holidays)

module.exports = router
